import { useContext } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AuthContext } from "../context/AuthContext";

const HomePage = () => {
  const { isAuthenticated, user } = useContext(AuthContext);
  const navigate = useNavigate();

  if (isAuthenticated) {
    const dashboardPath =
      user?.role?.toLowerCase() === "student"
        ? "/student/dashboard"
        : user?.role?.toLowerCase() === "faculty"
          ? "/faculty/dashboard"
          : "/admin/dashboard";
    navigate(dashboardPath, { replace: true });
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-blue-100">
      {/* Hero Section */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="text-center">
          <div className="text-6xl mb-4">🎓</div>
          <h1 className="text-5xl font-extrabold text-gray-900 mb-4">
            Smart Campus Management System
          </h1>
          <p className="text-xl text-gray-700 mb-8">
            A comprehensive platform for seamless campus communication and
            management
          </p>
          <div className="flex gap-4 justify-center">
            <Link
              to="/login"
              className="px-8 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition"
            >
              Sign In
            </Link>
            <Link
              to="/register"
              className="px-8 py-3 bg-white text-blue-600 border-2 border-blue-600 rounded-lg font-semibold hover:bg-blue-50 transition"
            >
              Sign Up
            </Link>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className="bg-white py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold text-center text-gray-900 mb-12">
            Key Features
          </h2>

          <div className="grid md:grid-cols-3 gap-8">
            {[
              {
                icon: "📅",
                title: "Class Timetable",
                description:
                  "View your personalized class schedule and manage timetables efficiently",
              },
              {
                icon: "📱",
                title: "QR Attendance",
                description:
                  "Mark attendance quickly by scanning QR codes generated by faculty",
              },
              {
                icon: "📄",
                title: "Notices & Announcements",
                description:
                  "Stay updated with important notices and announcements from faculty",
              },
              {
                icon: "💬",
                title: "Complaint Management",
                description:
                  "Submit and track complaints with an efficient resolution system",
              },
              {
                icon: "👥",
                title: "User Management",
                description:
                  "Complete user management system for students, faculty, and admins",
              },
              {
                icon: "📊",
                title: "Analytics & Reports",
                description:
                  "Comprehensive reporting and analytics for all campus activities",
              },
            ].map((feature, idx) => (
              <div key={idx} className="bg-gray-50 rounded-lg p-6 text-center">
                <div className="text-4xl mb-4">{feature.icon}</div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">
                  {feature.title}
                </h3>
                <p className="text-gray-600">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Role-based Section */}
      <div className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold text-center text-gray-900 mb-12">
            For Everyone
          </h2>

          <div className="grid md:grid-cols-3 gap-8">
            {[
              {
                role: "🎓 Students",
                features: [
                  "View personal timetable",
                  "Mark attendance via QR",
                  "View notices & announcements",
                  "Submit complaints",
                  "Track attendance history",
                ],
              },
              {
                role: "👨‍🏫 Faculty",
                features: [
                  "Create class timetables",
                  "Generate QR attendance codes",
                  "Create notices & announcements",
                  "Manage student attendance",
                  "View academic records",
                ],
              },
              {
                role: "⚙️ Administrators",
                features: [
                  "Manage all users",
                  "View complaints",
                  "Control notices & announcements",
                  "System reports & analytics",
                  "System configuration",
                ],
              },
            ].map((item, idx) => (
              <div key={idx} className="bg-white rounded-lg shadow-md p-8">
                <h3 className="text-2xl font-bold text-gray-900 mb-4">
                  {item.role}
                </h3>
                <ul className="space-y-2">
                  {item.features.map((feature, fidx) => (
                    <li
                      key={fidx}
                      className="flex items-start gap-2 text-gray-700"
                    >
                      <span className="text-green-600 mt-1">✓</span>
                      <span>{feature}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* CTA Section */}
      <div className="bg-gradient-to-r from-blue-600 to-blue-800 text-white py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to get started?</h2>
          <p className="text-lg mb-8 text-blue-100">
            Join Smart Campus today and streamline your academic experience
          </p>
          <div className="flex gap-4 justify-center">
            <Link
              to="/register"
              className="px-8 py-3 bg-white text-blue-600 rounded-lg font-semibold hover:bg-blue-50 transition"
            >
              Create Account
            </Link>
            <Link
              to="/login"
              className="px-8 py-3 bg-blue-500 text-white border-2 border-white rounded-lg font-semibold hover:bg-blue-400 transition"
            >
              Sign In
            </Link>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-300 py-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <p>
            &copy; 2024 Smart Campus Management System. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default HomePage;
