import { useContext, useEffect } from "react";
import {
  MdBarChart,
  MdCalendarMonth,
  MdCheckCircle,
  MdDescription,
  MdGroup,
  MdMessage,
  MdQrCode2,
  MdSchool,
  MdSettings,
} from "react-icons/md";
import { Link, useNavigate } from "react-router-dom";
import { AuthContext } from "../context/AuthContext";

const FEATURES = [
  {
    icon: <MdCalendarMonth size={36} className="text-blue-500" />,
    title: "Class Timetable",
    description:
      "View your personalized class schedule and manage timetables efficiently",
  },
  {
    icon: <MdQrCode2 size={36} className="text-green-500" />,
    title: "QR Attendance",
    description:
      "Mark attendance quickly by scanning QR codes generated by faculty",
  },
  {
    icon: <MdDescription size={36} className="text-orange-500" />,
    title: "Notices & Announcements",
    description:
      "Stay updated with important notices and announcements from faculty",
  },
  {
    icon: <MdMessage size={36} className="text-red-500" />,
    title: "Complaint Management",
    description:
      "Submit and track complaints with an efficient resolution system",
  },
  {
    icon: <MdGroup size={36} className="text-purple-500" />,
    title: "User Management",
    description:
      "Complete user management system for students, faculty, and admins",
  },
  {
    icon: <MdBarChart size={36} className="text-indigo-500" />,
    title: "Analytics & Reports",
    description:
      "Comprehensive reporting and analytics for all campus activities",
  },
];

const ROLES = [
  {
    icon: <MdSchool size={28} className="text-blue-500" />,
    role: "Students",
    features: [
      "View personal timetable",
      "Mark attendance via QR",
      "View notices & announcements",
      "Submit complaints",
    ],
  },
  {
    icon: <MdSchool size={28} className="text-green-500" />,
    role: "Faculty",
    features: [
      "Create class timetables",
      "Generate QR attendance codes",
      "Create notices & announcements",
      "Manage student attendance",
    ],
  },
  {
    icon: <MdSettings size={28} className="text-purple-500" />,
    role: "Administrators",
    features: [
      "Manage all users",
      "View complaints",
      "Control notices & announcements",
      "System reports & analytics",
    ],
  },
];

const HomePage = () => {
  const { isAuthenticated, user } = useContext(AuthContext);
  const navigate = useNavigate();

  useEffect(() => {
    if (isAuthenticated) {
      const path =
        user?.role === "STUDENT"
          ? "/student/dashboard"
          : user?.role === "FACULTY"
            ? "/faculty/dashboard"
            : "/admin/dashboard";
      navigate(path, { replace: true });
    }
  }, [isAuthenticated]);

  return (
    <div className="min-h-screen bg-linear-to-br from-blue-50 to-blue-100">
      {/* Hero */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 text-center">
        <MdSchool className="text-blue-600 mx-auto mb-4" size={72} />
        <h1 className="text-5xl font-extrabold text-gray-900 mb-4">
          Smart Campus Management System
        </h1>
        <p className="text-xl text-gray-700 mb-8">
          A comprehensive platform for seamless campus communication and
          management
        </p>
        <div className="flex gap-4 justify-center">
          <Link
            to="/login"
            className="px-8 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition"
          >
            Sign In
          </Link>
          <Link
            to="/register"
            className="px-8 py-3 bg-white text-blue-600 border-2 border-blue-600 rounded-lg font-semibold hover:bg-blue-50 transition"
          >
            Sign Up
          </Link>
        </div>
      </div>

      {/* Features */}
      <div className="bg-white py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold text-center text-gray-900 mb-12">
            Key Features
          </h2>
          <div className="grid md:grid-cols-3 gap-8">
            {FEATURES.map((f, i) => (
              <div key={i} className="bg-gray-50 rounded-lg p-6 text-center">
                <div className="flex justify-center mb-4">{f.icon}</div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">
                  {f.title}
                </h3>
                <p className="text-gray-600">{f.description}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Roles */}
      <div className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold text-center text-gray-900 mb-12">
            For Everyone
          </h2>
          <div className="grid md:grid-cols-3 gap-8">
            {ROLES.map((r, i) => (
              <div key={i} className="bg-white rounded-lg shadow-md p-8">
                <h3 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
                  {r.icon} {r.role}
                </h3>
                <ul className="space-y-2">
                  {r.features.map((feat, j) => (
                    <li
                      key={j}
                      className="flex items-start gap-2 text-gray-700"
                    >
                      <MdCheckCircle
                        className="text-green-600 mt-1 shrink-0"
                        size={16}
                      />
                      <span>{feat}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* CTA */}
      <div className="bg-linear-to-r from-blue-600 to-blue-800 text-white py-16">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to get started?</h2>
          <p className="text-lg mb-8 text-blue-100">
            Join Smart Campus today and streamline your academic experience
          </p>
          <div className="flex gap-4 justify-center">
            <Link
              to="/register"
              className="px-8 py-3 bg-white text-blue-600 rounded-lg font-semibold hover:bg-blue-50 transition"
            >
              Create Account
            </Link>
            <Link
              to="/login"
              className="px-8 py-3 bg-blue-500 text-white border-2 border-white rounded-lg font-semibold hover:bg-blue-400 transition"
            >
              Sign In
            </Link>
          </div>
        </div>
      </div>

      <footer className="bg-gray-900 text-gray-300 py-8">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <p>
            &copy; {new Date().getFullYear()} Smart Campus Management System.
            All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default HomePage;
